spring:
    application:
        name: websocket

    datasource:
        url: jdbc:mariadb://localhost:3306/final_project
        driver-class-name: org.mariadb.jdbc.Driver
        username: kosa
        password: 1004

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true