version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./server
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PASSWORD: 1004
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/slgi_emr_db?useSSL=false
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_PASSWORD: 1004

    depends_on:
      - redis
      - mariadb

  mariadb:
    build:
      context: ./mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1004
      MARIADB_DATABASE: slgi_emr_db

  redis:
    build:
      context: ./redis
