version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=1004

  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
