version: "3"
services:

  mariadb:
    build:
      context: ./mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1004
      MARIADB_DATABASE: slgi_emr_db
    volumes:
      - ./mariadb/data:/var/lib/mysql

  redis:
    build:
      context: ./redis

  backend:
    build:
      context: ./server
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PASSWORD: 1004
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/slgi_emr_db?useSSL=false
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_PASSWORD: 1004
    volumes:
      - ./server/build/libs/server-0.0.1-SNAPSHOT.jar:/app/app.jar
    depends_on:
      - redis
      - mariadb

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
