spring:
    application:
        name: slgi

    datasource:
        url: #jdbc:mariadb://localhost:3306/DATABASE_NAME?useSSL=false
        driver-class-name: org.mariadb.jdbc.Driver
        username: #USERNAME
        password: #PASSWORD

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
