spring:
    application:
        name: server

    devtools:
      livereload:
        enabled: true

    profiles:
      active: env

server:
  port: 8080

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.emr.slgi.mybatis.typehandler
#  type-aliases-package: com.emr.slgi.member

springdoc:
  swagger-ui:
    path: /api-docs
