spring:
    application:
        name: server

    datasource:
        url: jdbc:mariadb://localhost:3306/kosa_db?useSSL=false
        driver-class-name: org.mariadb.jdbc.Driver
        username: kosa
        password: 1004

    devtools:
      livereload:
        enabled: true

server:
  port: 8080

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
#  type-aliases-package: com.emr.slgi.member
