name: SlgiEMR
on: 
  push: # 동작시 어떤 것을 가지고 동작할 것인가
    branches: [git-action]
  workflow_dispatch:
env: # 환경 설정 변수
  REPOSITORY_NAME: msa-medical
  
jobs:
    
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: 깃 클론
        uses: actions/checkout@v3

      - name: 자바 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Server 빌드
        run: |
          cd server
          chmod +x gradlew
          ./gradlew bootJar

      - name: Frontend 빌드
        run: |
          cd frontend
          npm install
          npm run build

      - name: EC2에서 DockerHub에 로그인
        uses: docker/login-action@v1
        with:
          username: ${{secrets.USERNAME}} 
          password: ${{secrets.PASSWORD}} 

      - name: 백엔드 이미지 빌드 및 푸시
        run: |
          docker build -t ${{secrets.USERNAME}}/SlgiEMRBackend ./server
          docker push ${{secrets.USERNAME}}/SlgiEMRBackend

      - name: 프론트엔드 이미지 빌드 및 푸시
        run: |
          docker build -t ${{secrets.USERNAME}}/SlgiEMRFrontend ./frontend
          docker push ${{secrets.USERNAME}}/SlgiEMRFrontend

  deploy:
    needs: build
    name: EC2에 배포
    runs-on: [ubuntu-latest]
    steps:
      - name: 운영서버에서 DockerHub에 로그인
        uses: docker/login-action@v1
        with:
          username: ${{secrets.USERNAME}} 
          password: ${{secrets.PASSWORD}} 
          
      - name: Docker Hub에서 다운로드
        run: docker-compose pull
      
      - name: docker-compose 재실행
        run: |
          docker-compose down
          docker-compose up -d
  
